// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SampletestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sampletest() {
    driver.get("https://www.google.com/search?q=audi&sxsrf=APwXEdfUTe_EL31AfxY7zPYiRjGjiDLhEQ%3A1686648114102&source=hp&ei=MjWIZOqaBJqi-Qap4oeoAg&iflsig=AOEireoAAAAAZIhDQp23oPt_bVqqXJtx_0CsxuhqWnrw&gs_ssp=eJzjYtfP1TfINjVQYDRgdGDwYkksTckEACmsBGA&oq=audi&gs_lcp=Cgdnd3Mtd2l6EAMYADINCC4QxwEQ0QMQigUQJzIHCCMQigUQJzITCC4QigUQsQMQgwEQxwEQ0QMQQzIICAAQgAQQsQMyCAgAEIAEELEDMgsIABCABBCxAxCDATILCAAQgAQQsQMQgwEyCAgAEIAEELEDMggILhCABBCxAzILCAAQigUQsQMQgwE6CwguEIoFELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoUCC4QgAQQsQMQgwEQxwEQ0QMQ1AI6BQguEIAEOg0ILhCKBRDHARDRAxAnOgcIABCKBRBDOgoIABCKBRCxAxBDUABYiwVgghBoAHAAeACAAbUCiAGIB5IBBzAuMS4yLjGYAQCgAQE&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1066, 812));
    {
      WebElement element = driver.findElement(By.cssSelector(".eKjLze .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".eKjLze .LC20lb")).click();
  }
}
